rename_columns = {"Timestamp": "thoi_gian",
                      "Tên nhân viên": "tranner",
                      "Tên thương hiệu": "brand_name",
                      "Mã đăng nhập của cửa hàng": "brand_office_code",
                      "1. Hình thức check code": "hinh_thuc_check_code",
                      "2. Tình trạng hoạt động của cửa hàng": "brand_office_status",
                      "Địa chỉ mới (Số nhà/Đường phố, ngõ nghách/Phường,xã/Quận,huyện/Thành phố, tỉnh thành)": "address_new",
                      "3. POSM cần bổ sung (CH mới) [POSM cần bổ sung (CH mới)]": "3_posm_can_bo_sung",
                      "3. POSM cần bổ sung [3.1 POSM đã đặt trước đó]": "3_1_posm_da_dat_truoc",
                      "3. POSM cần bổ sung [3.2 POSM cần bổ sung]": "3_1_posm_dat_moi",
                      "5. Đại diện cửa hàng (Tên của NVCH trực tiếp trao đổi)": "5_dai_dien_cua_hang",
                      "5.1 Số điện thoại liên hệ (của NVCH trực tiếp trao đổi/SĐT của CH/Tên+SĐT quản lý CH nhưng phải ghi chú)": "5_1_sdt_lien_he",
                      "5. Đại diện cửa hàng (Tên của NVCH trực tiếp trao đổi)": "5_dai_dien_cua_hang_1",
                      "5.1 Số điện thoại liên hệ (của NVCH trực tiếp trao đổi/SĐT của CH/Tên+SĐT quản lý CH nhưng phải ghi chú)": "5_1_sdt_lien_he_1",
                      "6.1 Mức độ nhận diện UrBox": "muc_do_nhan_dien_urbox",
                      "6.2 Thái độ hợp tác": "thai_do_hop_tac",
                      "6.3 Thao tác với UrBox": "thao_tac_voi_urbox",
                      "6.1. Lý do Không Đạt - Mức độ nhận diện UrBox": "6_1_ly_do_khong_dat",
                      "6.2. Lý do Không Đạt - Thái độ hợp tác": "6_2_ly_do_khong_dat",
                      "6.3. Lý do Không Đạt - Thao tác với UrBox": "6_3_ly_do_khong_dat",
                      "7.1. NV Trainers đã hướng dẫn kích hoạt code": "7_1_trainers_da_huong_dan_kich_hoat_code",
                      "7.2 NV Trainers đã hướng dẫn kích hoạt code - Lý do Không Đạt": "7_2_ly_do_khong_dat",
                      "7.3 Ghi chú khác (Tên+ SĐT của Quản lý CH, Địa chỉ của CH nếu CH chưa có mã , Các góp ý về CTKM của đối thủ...)": "7_3_ghi_chu_khac",
                      "Recheck off cửa hàng": "recheck_off",
                      "Test": "test",
                      "Cơ chế test": "cơ chế test",
                      }
QUERY = """
INSERT into ub_rawdata.cs_data_tranning (
	thoi_gian,
	tranner,
	brand_name,
	brand_office_code,
	hinh_thuc_check_code,
	brand_office_status,
	address_new,
	"3_posm_can_bo_sung",
	"3_1_posm_da_dat_truoc",
	"3_1_posm_dat_moi",
	"5_dai_dien_cua_hang_1",
	"5_1_sdt_lien_he_1",
	muc_do_nhan_dien_urbox,
	thai_do_hop_tac,
	thao_tac_voi_urbox,
	"6_1_ly_do_khong_dat",
	"6_2_ly_do_khong_dat",
	"6_3_ly_do_khong_dat",
	"7_1_trainers_da_huong_dan_kich_hoat_code",
	"7_2_ly_do_khong_dat",
	"7_3_ghi_chu_khac",
	recheck_off,
	test,
	"Cơ chế test"
) SELECT 
	thoi_gian,
	tranner,
	brand_name,
	brand_office_code,
	hinh_thuc_check_code,
	brand_office_status,
	address_new,
	"3_posm_can_bo_sung",
	"3_1_posm_da_dat_truoc",
	"3_1_posm_dat_moi",
	"5_dai_dien_cua_hang_1",
	"5_1_sdt_lien_he_1",
	muc_do_nhan_dien_urbox,
	thai_do_hop_tac,
	thao_tac_voi_urbox,
	"6_1_ly_do_khong_dat",
	"6_2_ly_do_khong_dat",
	"6_3_ly_do_khong_dat",
	"7_1_trainers_da_huong_dan_kich_hoat_code",
	"7_2_ly_do_khong_dat",
	"7_3_ghi_chu_khac",
	recheck_off,
	test,
	"Cơ chế test"
from sentry.cs_data_tranning
"""